# Generated by Django 5.0.4 on 2024-10-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animedata',
            name='is_movie',
            field=models.BooleanField(default=False),
        ),
    ]
