# Generated by Django 5.0.4 on 2024-10-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('year_of_release', models.IntegerField()),
            ],
        ),
    ]
